var userInformation = [
                    {
                        id :1,
                        course  :'Data Structures',
                        someInformation : ' Data structures are designed to organize data in order to suit specific purposes so as to access and perform operations in an appropriate manner.Anyone with a PC and internet connection can join online data structures and algorithms course. ', 
                        teacher: 'Md.Ismail',
                        img:'https://i.ibb.co/QN534gy/pic3.jpg',
                        email :'psharpe@mac.com',
                        time:'3 Months',
                        courseFee : 200,
                    },
                    {
                        id:2,
                        course : 'Data Science',
                        someInformation :'Data science is an inter-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from many structural and unstructured data. Data science is related to data mining, machine learning and big data.',
                        teacher : 'Md.Sovon',
                        img:'https://i.ibb.co/k2LdDqK/pic6.jpg',
                        email :'magusnet@icloud.com',
                        time :'6 Months',
                        courseFee: 300,
                    },
                    {
                        id:3,
                        course : 'Core JavaScript',
                        someInformation :'Core JavaScript is the base part of the JavaScript language that is supported on both the client and server side. Client-side JavaScript (CSJS) contains the core JavaScript elements and has several additional objects, properties and methods that are supported by browsers.',
                        teacher : 'Md.Zillur',
                        img:'https://i.ibb.co/c8SdCn8/pic7.jpg',
                        email :'hillct@verizon.net',
                        time:'2 Month 3 week',
                        courseFee :100,
                    },
                    {
                        id:4,
                        course :'Python',
                        someInformation:'Python is a general-purpose programming language, meaning it can be used for many different things. Python is used for web development, AI, machine learning, operating systems, mobile application development, and some video games.',
                        teacher : 'Md. Masum Miah',
                        img:'https://i.ibb.co/hYj7Jnp/pic13.jpg',
                        email :'dunstan@att.net',
                        time:'3 Months',
                        courseFee:200,
                    },
                    {
                        id:5,
                        course : 'Machine Learning',
                        someInformation :'Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it learn for themselves.',
                        teacher:'Md.Hasib Hasan',
                        img:'https://i.ibb.co/W0TxD0W/pic9.jpg',
                        email:'tmccarth@sbcglobal.net',
                        time:'8 Months',
                        courseFee:600,
                    },
                    {
                        id:6,
                        course:'Java',
                        someInformation:'Java can be used to create complete applications that may run on a single computer or be distributed among servers and clients in a network. It can also be used to build a small application module or applet (a simply designed, small application) for use as part of a Web page.',
                        teacher:'Sohan Ahamed',
                        img:'https://i.ibb.co/jHLvXbC/pic10.jpg',
                        email:'lipeng@mac.com',
                        time:'4 Months',
                        courseFee:300,
                    },
                    {
                        id:7,
                        course:'Simple C Programming Language',
                        someInformation :'Although numerous computer languages are used for writing computer applications, the computer programming language, C, is the most popular language worldwide. Everything from microcontrollers to operating systems is written in C ',
                        teacher:'Hafizul Islam',
                        email:"hafizul@gmail.com",
                        img:'https://i.ibb.co/tHbG98Z/pic11.jpg',
                        time:'3 Months',
                        courseFee:130,
                    },
                    {
                        id:8,
                        course:'Database',
                        someInformation:'A database is an organized collection of structured information, or data, typically stored electronically in a computer system. A database is usually controlled by a database management system (DBMS).',
                        teacher:'Kamrul Hasan Komol',
                        img:'https://i.ibb.co/N9ZcwJz/pic12.jpg',
                        email:'baveja@me.com',
                        time:'2 Months',
                        courseFee:100,
                    },
                    {
                        id:9,
                        course:'HTML and CSS/SCSS',
                        someInformation:'HTML (the Hypertext Markup Language) and CSS (Cascading Style Sheets) are two of the core technologies for building Web pages. HTML provides the structure of the page, CSS the (visual and aural) layout, for a variety of devices.',
                        teacher:'Samim Hasan',
                        img:'https://i.ibb.co/Zh6Nkvy/pic1.jpg',
                        email:'samim@gmail.com',
                        time:'1 Month',
                        courseFee:120,
                    },
                    {
                        id:10,
                        course :'MongoDB',
                        someInformation:'MongoDB is a document database with the scalability and flexibility that you want with the querying and indexing that you need.',
                        teacher:'Sotez Khan',
                        img:'https://i.ibb.co/Wnw7qPW/pic4.jpg',
                        email:'sotezkhan11@gmail.com',
                        time:'1 Month',
                        courseFee:220,
                    },
                    {
                        id:11,
                        course:'Robotics',
                        someInformation:'Robotics is a branch of engineering that involves the conception, design, manufacture, and operation of robots. This field overlaps with computer engineering, computer science (especially artificial intelligence), electronics, mechatronics, mechanical, nanotechnology and bioengineering.',
                        teacher:'Alamin',
                        img:'https://i.ibb.co/tHbG98Z/pic11.jpg',
                        email:'alamin@gmail.com',
                        time:'6 Months',
                        courseFee:'500',
                    },
                    {
                        id:12,
                        course:'Web Development',
                        someInformation :'Web development is the work involved in developing a Web site for the Internet (World Wide Web) or an intranet (a private network). ... Among Web professionals, "Web development" usually refers to the main non-design aspects of building Web sites: writing markup and coding.',
                        teacher:'Md.Suvo Miah',
                        img:'https://i.ibb.co/W0TxD0W/pic9.jpg',
                        email:'dulalmiah70112@gmail.com',
                        time:'5 Months',
                        courseFee:5500,
                    }
                      ]
export default userInformation;